@startuml
agent "Measure Source"
agent "Measure Consumer"
storage "External Storage"
agent "EHR System"
agent "Interface Engine"
database "System Database"
agent "Bed Management"
agent "Central Monitoring"
agent "ED System"
agent "Equipment Tracking"
@enduml
