@startuml
!pragma graphviz_dot smetana
rectangle "Hospital EHR System" {
agent "Measure Source" as MeasureSource
}

rectangle "Public Health Agency" {
agent "Measure Consumer\n<i>(FHIR Server)</i>" as MeasureConsumer
}
MeasureSource -> MeasureConsumer : Push with API

@enduml
