@startuml
rectangle "Hospital EHR System" {
agent "Measure Source" as MeasureSource
}

rectangle "Public Health Agency" {
storage "External Storage" as ExternalStorage
agent "Measure Consumer" as MeasureConsumer
}

MeasureSource -> ExternalStorage : Push with Dump
ExternalStorage <- MeasureConsumer : Pull with Dump

@enduml
