@startuml

agent "Measure Definition Source" as MeasureDefinitionSource

agent "Measure Definition Consumer" as MeasureDefinitionConsumer
usecase (Query Measure Definition) as (PULL-MX)
MeasureDefinitionSource --> (PULL-MX)
MeasureDefinitionConsumer --> (PULL-MX)
@enduml
