@startuml
hide footbox
actor "Public Health User"
participant "Measure Aggregating System [Measure Intermediary]" as MeasureIntermediary
participant "Measure Reporting and Analytics System [Measure Consumer]" as MeasureConsumer
participant "Reporting Sources [Measure Source]" as MeasureSource
"MeasureIntermediary" -> "MeasureSource" : 1. Measure Intermediary aggregates data from one or Measure Sources
activate "MeasureIntermediary"
activate "MeasureSource"
return
deactivate "MeasureIntermediary"
deactivate "MeasureSource"
"Public Health User" -> "MeasureConsumer" : 2. User Initiates Search
activate "Public Health User"
activate "MeasureConsumer"
"MeasureConsumer" -> "MeasureIntermediary" : 3. Get Aggregated Results
activate "MeasureIntermediary"
"MeasureIntermediary" --> "MeasureConsumer" : 4. Aggregated Results
deactivate "MeasureIntermediary"
"MeasureConsumer" --> "Public Health User" : 5. Display Results
deactivate "Public Health User"
deactivate "MeasureConsumer"
"Public Health User" -> "MeasureConsumer" : 6. User refines Focus or Form of Display
activate "Public Health User"
activate "MeasureConsumer"
"MeasureConsumer" -> "MeasureIntermediary" : 7. Get Aggregated Results
activate "MeasureIntermediary"
"MeasureIntermediary" --> "MeasureConsumer" : 8. Aggregated Results
deactivate "MeasureIntermediary"
"MeasureConsumer" --> "Public Health User" : 9. Display Refined Results
deactivate "Public Health User"
deactivate "MeasureConsumer"
@enduml
