@startuml
hide footbox
participant "Reporting Organization [Measure Definition Consumer]" as MeasureDefinitionConsumer
participant "Hospital Reporting System Public Health Agency [Measure Computer]" as MeasureComputer
participant "Defining Agency [Measure Definition Source]" as MeasureDefinitionSource
participant "Hospital EHR System [Data Source]" as DataSource
participant "Measure Consumer" as MeasureConsumer
"MeasureDefinitionConsumer" -> "MeasureDefinitionSource" : 1. Query for New or Updated Measures
activate "MeasureDefinitionConsumer"
activate "MeasureDefinitionSource"
return
deactivate "MeasureDefinitionConsumer"
deactivate "MeasureDefinitionSource"
"MeasureComputer" -> "MeasureComputer" : 2. Compute Measure
activate "MeasureComputer"
activate "MeasureComputer"
"MeasureComputer" -> "DataSource" : 3. Gather Data
activate "DataSource"
"DataSource" --> "MeasureComputer" : 4. Returns Matching FHIR Resources
deactivate "DataSource"
deactivate "MeasureComputer"
deactivate "MeasureComputer"
"MeasureComputer" -> "MeasureConsumer" : 5. Send Measures to a Measure Consumer
activate "MeasureComputer"
activate "MeasureConsumer"
return
deactivate "MeasureComputer"
deactivate "MeasureConsumer"
@enduml
