@startuml
!pragma graphviz_dot smetana
rectangle "FHIR Server" as MeasureIntermediary {
agent "Measure Source" as MeasureSource1
agent "Measure Consumer" as MeasureConsumer1
MeasureSource1 == MeasureConsumer1
}

rectangle "Slicer" as MeasureIntermediary2 {
agent "Measure Consumer" as MeasureConsumer2
agent "Measure Source" as MeasureSource2
MeasureConsumer2 ==> MeasureSource2 : Transform\nfrom\n Measure to\nGroup
}

MeasureConsumer2 -> MeasureSource1 : "    Pull API    \n(Measure)"
MeasureSource2 -> MeasureConsumer1 : "    Push API    \n(Group)"

@enduml
