@startuml
!pragma graphviz_dot smetana
agent "Measure Source" as MeasureSource

agent "Measure Consumer" as MeasureConsumer

agent "Measure Computer" as MeasureComputer

agent "Data Source" as DataSource
usecase (Compute Measure) as (COMPUTE-MX)
MeasureSource --> (COMPUTE-MX)
MeasureConsumer --> (COMPUTE-MX)
MeasureComputer --> (COMPUTE-MX)
DataSource --> (COMPUTE-MX)
@enduml
